# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: true
copyright_year: '2026'
email: annethessen@gmail.com
full_name: diatomsRcool
gh_action_docs_preview: true
gh_action_pypi: true
github_org: linkml
license: MIT
project_description: This is a LinkML schema for CDEs
project_name: linkml-microschema-profile
project_slug: linkml_microschema_profile

